export const posts = [
  {
    id: "1",
    title: "Apple launches new AI features for iOS, Apple launches new AI features for iOS",
    headerTitle: "technology",
    tag: "/tech",
    votes: 124,
    avatar: require("../assets/images/post.webp"),
  },
  {
    id: "2",
    title: "India wins historic test match against England, India wins historic test match against England",
    headerTitle: "sports",
    tag: "/cricket",
    votes: 89,
    avatar: require("../assets/images/post.webp"),
  },
  {
    id: "3",
    title: "NASA discovers new Earth-like planet, NASA discovers new Earth-like planet",
    headerTitle: "science",
    tag: "/space",
    votes: 156,
    avatar: require("../assets/images/post.webp"),
  },
  {
    id: "4",
    title: "Top 10 JavaScript frameworks in 2025, Top 10 JavaScript frameworks in 2025",
    headerTitle: "programming",
    tag: "/coding",
    votes: 201,
    avatar: require("../assets/images/post.webp"),
  },
  {
    id: "5",
    title: "Stock market hits all-time high, Stock market hits all-time high",
    headerTitle: "business",
    tag: "/finance",
    votes: 77,
    avatar: require("../assets/images/post.webp"),
  },
  {
    id: "6",
    title: "New electric car breaks charging record, New electric car breaks charging record",
    headerTitle: "automobile",
    tag: "/ev",
    votes: 134,
    avatar: require("../assets/images/post.webp"),
  },
  {
    id: "7",
    title: "Best travel destinations for 2025, Best travel destinations for 2025",
    headerTitle: "travel",
    tag: "/explore",
    votes: 65,
    avatar: require("../assets/images/post.webp"),
  },
  {
    id: "8",
    title: "Healthy morning routines backed by science, Healthy morning routines backed by science",
    headerTitle: "lifestyle",
    tag: "/health",
    votes: 98,
    avatar: require("../assets/images/post.webp"),
  },
];
